apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  url: https://gaurav-garv4u.github.io/k8s-ingress-controller/ 
  #url: https://kubernetes.github.io/ingress-nginx
